AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
  ForceEqualSignAlignment: true

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Style/HashSyntax:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Enabled: true
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
